import { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { I18nProvider } from '../lib/i18n'
import { getNativeCaps, listCapsBusinesses, listCapsAccounts, saveCaps, type CapsAccount, type Snapshot } from '../lib/adsCaps'
import { AdsCapsSetup } from './AdsCapsSetup'
vi.mock('../lib/adsCaps', async () => ({ ...await vi.importActual('../lib/adsCaps'), getNativeCaps: vi.fn(), listCapsBusinesses: vi.fn(), listCapsAccounts: vi.fn(), saveCaps: vi.fn() }))
const business = '11111111-1111-4111-8111-111111111111'
const account: CapsAccount = { account_ref: 'google:1234567890', platform: 'google', platform_account_id: '1234567890', display_name: null, currency: 'EUR', guardrail: null }
const snapshot: Snapshot = { revision: 'a'.repeat(64), loaded_digest: 'a'.repeat(64), accounts: {} }
let host: HTMLDivElement, root: Root
const close = vi.fn()
async function render() { await act(async () => { root.render(<I18nProvider><AdsCapsSetup getCsrf={() => 'csrf'} onClose={close} /></I18nProvider>) }) }
function button(text: string) { return [...host.querySelectorAll('button')].find(node => node.textContent === text)! }
async function click(text: string) { await act(async () => { button(text).click() }) }
async function fill() { await act(async () => { [...host.querySelectorAll('input')].forEach((node, index) => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!.call(node, ['10','100','0','10','15','2'][index]); node.dispatchEvent(new Event('input', { bubbles: true })) }) }) }
beforeEach(() => { localStorage.clear(); vi.resetAllMocks(); vi.mocked(getNativeCaps).mockResolvedValue(snapshot); vi.mocked(listCapsBusinesses).mockResolvedValue([{ business_id: business, name: 'Clinic' }]); vi.mocked(listCapsAccounts).mockResolvedValue([account]); vi.mocked(saveCaps).mockResolvedValue(null); host = document.createElement('div'); document.body.append(host); root = createRoot(host) })
afterEach(() => { act(() => root.unmount()); host.remove() })
it('shows a connected account with empty amounts and no automatic save', async () => { await render(); expect(host.textContent).toContain('1234567890'); expect(host.textContent).toContain('(EUR)'); expect([...host.querySelectorAll('input')].every(node => node.value === '')).toBe(true); expect(saveCaps).not.toHaveBeenCalled(); expect((button('Confirmar y aplicar límites') as HTMLButtonElement).disabled).toBe(true); expect(document.activeElement).toBe(host.querySelector('h2')) })
it('requires explicit owner input, preserves zero and reports cancellation', async () => { await render(); await fill(); await click('Confirmar y aplicar límites'); expect(saveCaps).toHaveBeenCalledExactlyOnceWith(business, account, snapshot, { daily_cap_minor:1000,monthly_cap_minor:10000,floor_minor:0,ceiling_minor:1000,max_step_pct:15,max_changes_per_day:2 }, 'csrf'); expect(host.textContent).toContain('Guardado cancelado'); expect(localStorage.getItem('ads_caps')).toBeNull() })
it('does not claim caps verified when broker digest differs or SQL is missing', async () => { vi.mocked(getNativeCaps).mockResolvedValue({ ...snapshot, loaded_digest:'b'.repeat(64), accounts: { '1234567890': { daily_cap_minor:1000,monthly_cap_minor:10000,floor_minor:0,ceiling_minor:1000,max_step_pct:15,max_changes_per_day:2,autonomy_enabled:false } } }); await render(); expect(host.textContent).toContain('todavía no tiene todos sus límites verificados'); expect(host.textContent).not.toContain('Límites actuales verificados.') })
it('shows safe errors and can recheck after a failed owner query', async () => { vi.mocked(listCapsBusinesses).mockRejectedValueOnce(new Error('private bearer secret')); await render(); expect(host.querySelector('[role=alert]')).not.toBeNull(); expect(host.textContent).not.toContain('private'); await click('Volver a comprobar'); expect(host.querySelectorAll('input')).toHaveLength(6) })
it('keeps save single-flight and reports unverified rollback without success', async () => { let fail!: (reason: unknown) => void; vi.mocked(saveCaps).mockImplementation(() => new Promise((_ok,no) => { fail = no })); await render(); await fill(); await act(async () => { button('Confirmar y aplicar límites').click(); button('Confirmar y aplicar límites').click() }); expect(saveCaps).toHaveBeenCalledOnce(); expect((button('Cerrar') as HTMLButtonElement).disabled).toBe(true); await act(async () => fail(new Error('ads_caps_rollback_unknown'))); expect(host.textContent).toContain('No apruebes campañas'); expect(host.textContent).not.toContain('Límites aplicados y verificados.') })
it('blocks currencies unsupported by the current SQL contract', async () => { vi.mocked(listCapsAccounts).mockResolvedValue([{ ...account,currency:'JPY' }]); await render(); await fill(); expect(host.textContent).toContain('monedas con dos decimales'); expect((button('Confirmar y aplicar límites') as HTMLButtonElement).disabled).toBe(true) })
it('has English labels without untranslated control text', async () => { localStorage.setItem('safent_ui_locale', 'en'); await render(); expect(host.querySelector('h2')?.textContent).toBe('Spending limits'); expect(button('Confirm and apply limits')).toBeDefined(); expect(host.textContent).toContain('Ad account') })
