"""hermes-mirror entrypoint — servicio de USUARIO en la sesión Hermes Shell.

Espera a que mutter exponga RemoteDesktop, levanta la sesión espejo (captura +
input), arranca la captura JPEG y sirve el WebSocket en 127.0.0.1:6080.

Auth layers:
  Layer 1 — per-session token (/etc/hermes/remote-token, ≥128-bit entropy).
             Generated at first boot by hermes-remote-token-gen.service.
  Layer 2 — Cloudflare Access JWT verification (CF_ACCESS_AUD + CF_ACCESS_TEAM_DOMAIN
             from /etc/hermes/cf-access.env or environment variables).

Fail-closed rules:
  - No token file → service refuses to start.
  - Token shorter than MIN_TOKEN_BYTES characters → service refuses to start.
  - CF Access not configured (no AUD/team_domain) → service WARNS and refuses
    to start UNLESS HERMES_MIRROR_CF_ACCESS_BYPASS_LOCAL=true (for LAN-only
    use without the tunnel; never set this in production).

Run:  python3 -m hermes.shell_server.mirror [--systemd-notify]
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
import time
from pathlib import Path

logger = logging.getLogger("hermes-mirror")

_TOKEN_PATH = Path(os.environ.get("HERMES_MIRROR_TOKEN_FILE", "/etc/hermes/remote-token"))
_PORT = int(os.environ.get("HERMES_MIRROR_PORT", "6080"))
_HOST = os.environ.get("HERMES_MIRROR_HOST", "127.0.0.1")

# 128 bits ÷ log2(58) ≈ 21.8 → 22 characters minimum.
# The token-gen service generates 24, giving ~144 bits.  We enforce ≥22.
_MIN_TOKEN_CHARS = 22


def _token() -> str:
    if _TOKEN_PATH.exists():
        return _TOKEN_PATH.read_text(encoding="utf-8").strip()
    return os.environ.get("HERMES_MIRROR_TOKEN", "").strip()


def _validate_token(token: str) -> None:
    """Raise SystemExit with an explanatory message if the token is too short."""
    if len(token) < _MIN_TOKEN_CHARS:
        logger.error(
            "hermes.mirror.weak_token — token has %d chars, minimum is %d. "
            "The token must be generated by hermes-remote-token-gen.service "
            "(24 base-58 chars from /dev/urandom). Refusing to start.",
            len(token),
            _MIN_TOKEN_CHARS,
        )
        sys.exit(1)


def _check_cf_access_config() -> None:
    """Warn and exit if CF Access is not configured and bypass is not set."""
    bypass = os.environ.get("HERMES_MIRROR_CF_ACCESS_BYPASS_LOCAL", "").lower() in (
        "true", "1", "yes"
    )
    if bypass:
        logger.warning(
            "hermes.mirror.cf_access.bypass_local=true — "
            "Cloudflare Access JWT verification is DISABLED. "
            "Only use this for local/LAN access without the Cloudflare tunnel."
        )
        return

    from .cf_access_verifier import CfAccessNotConfigured, _resolve_config  # noqa: PLC0415
    try:
        team_domain, aud = _resolve_config()
        logger.info(
            "hermes.mirror.cf_access.configured team=%s aud_prefix=%s…",
            team_domain,
            aud[:8] if len(aud) >= 8 else aud,
        )
    except CfAccessNotConfigured as exc:
        logger.error(
            "hermes.mirror.cf_access.not_configured — REFUSING TO START. "
            "Set CF_ACCESS_TEAM_DOMAIN and CF_ACCESS_AUD in "
            "/etc/hermes/cf-access.env or as environment variables. "
            "Or set HERMES_MIRROR_CF_ACCESS_BYPASS_LOCAL=true for "
            "local-only/LAN use. Details: %s",
            exc,
        )
        sys.exit(1)


def _sd_notify(message: str) -> None:
    sock = os.environ.get("NOTIFY_SOCKET")
    if not sock:
        return
    import socket  # noqa: PLC0415

    if sock.startswith("@"):
        sock = "\0" + sock[1:]
    try:
        with socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM) as s:
            s.connect(sock)
            s.sendall(message.encode())
    except OSError as exc:
        logger.warning("sd_notify failed: %s", exc)


def _wait_for_mutter(timeout_s: int = 90) -> bool:
    """Espera a que org.gnome.Mutter.RemoteDesktop esté en el bus de sesión."""
    import gi  # noqa: PLC0415

    gi.require_version("Gio", "2.0")
    from gi.repository import Gio, GLib  # noqa: PLC0415

    bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        try:
            reply = bus.call_sync(
                "org.freedesktop.DBus", "/org/freedesktop/DBus",
                "org.freedesktop.DBus", "NameHasOwner",
                GLib.Variant("(s)", ("org.gnome.Mutter.RemoteDesktop",)),
                None, Gio.DBusCallFlags.NONE, -1, None,
            )
            if reply.unpack()[0]:
                return True
        except Exception:  # noqa: BLE001
            pass
        time.sleep(2)
    return False


def main() -> int:
    from hermes.logging_setup import configure_structured_logging  # noqa: PLC0415

    configure_structured_logging(service="hermes-mirror", version="0.1.0")
    systemd_notify = "--systemd-notify" in sys.argv[1:]

    # --- Layer 1: token ---
    token = _token()
    if not token:
        logger.error("hermes.mirror.no_token — %s ausente", _TOKEN_PATH)
        return 1
    _validate_token(token)

    # --- Layer 2: Cloudflare Access config gate ---
    _check_cf_access_config()

    if not _wait_for_mutter():
        logger.error("hermes.mirror.no_mutter — RemoteDesktop no apareció")
        return 1

    from .jpeg_source import JpegFrameSource  # noqa: PLC0415
    from .mutter_mirror import MutterMirrorSession  # noqa: PLC0415
    from .server import MirrorServer  # noqa: PLC0415

    mirror = MutterMirrorSession()
    node_id = mirror.start()
    source = JpegFrameSource(node_id)
    source.start()
    logger.info("hermes.mirror.ready node=%s port=%s", node_id, _PORT)

    server = MirrorServer(
        source=source, mirror=mirror, token=token, host=_HOST, port=_PORT
    )

    if systemd_notify:
        _sd_notify("READY=1\nSTATUS=hermes-mirror ready\n")

    try:
        asyncio.run(server.run())
    except KeyboardInterrupt:
        pass
    finally:
        source.stop()
        mirror.stop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
